routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(
	[
		'namespace' => 'Front\Heng',
		'as' 		=> 'f.heng.',
	],
	function() {
		Route::get('/', 'HomeController@index' )->name('home');

		/*
			email verification link url
		 */
		Route::get( 'verify/member/{token}', [ 'as' => 'user.verify_member', 'uses' => 'UserController@verify_member' ]);
		Route::get( 'verify/newsletter/{token}', [ 'as' => 'user.verify_newsletter', 'uses' => 'UserController@verify_subscriber' ]);
		Route::get( 'verify/forgot-password/{token}', [ 'as' => 'user.verify_forgot_password', 'uses' => 'AuthController@verify_forgot_password' ]);

		Route::group(
			[
				'middleware' => [ 'auth.frontend.guest' ]
			],
		function()
		{
			/**
			 * AUTH
			 */
			Route::get( 'register', 'AuthController@register' )->name( 'auth.register' );
			Route::post( 'register', 'AuthController@store_register' )->name( 'auth.store_register' );

			/**
			 * request new verification
			 */
			Route::get( 'request/verification/{email?}', 'AuthController@request_verification' )->name( 'auth.request_verification' );


			Route::get( 'login', 'AuthController@login' )->name( 'auth.login' );
			Route::post( 'login', 'AuthController@auth' )->name( 'auth.auth' );

			Route::get( 'login/facebook', 'AuthController@login_facebook' )->name( 'auth.login_facebook' );

		});

		Route::group(
			[
				'middleware' => [ 'auth.frontend' ]
			],
		function()
		{
			/**
			 * AUTH
			 */
			Route::get( 'logout', 'AuthController@logout' )->name( 'auth.logout' );

			Route::get( 'update-password', 'AuthController@update_password' )->name( 'auth.update_password' );
			Route::get( 'success-password', 'AuthController@success_password' )->name( 'auth.success_password' );

			/**
			 * SELF - USER
			 */
			Route::get( 'self/dashboard', 'UserController@dashboard' )->name( 'users.dashboard' );
			Route::get( 'self/list/redemptions', 'UserController@redemption_list' )->name( 'users.redemption_list' );

			Route::get( 'self/delete/contest/{id}', 'UserController@delete_contest' )->name( 'users.delete_contest' );
			Route::get( 'self/contest/{status}', 'UserController@list_contests' )->name( 'users.list_contests' );

			Route::post( 'self/delete/contest', 'UserController@multi_delete_contest' )->name( 'users.multi_delete_contest' );

			Route::get( 'self/contest-summary', 'UserController@contest_summary' )->name( 'users.contest_summary' );

			Route::get( 'self/my-account', 'UserController@my_account' )->name( 'users.my_account' );
			Route::post( 'self/my-account', 'UserController@store_profile' )->name( 'users.my_account' );

			Route::get( 'self/resend/verification', 'UserController@resend_verification' )->name( 'users.resend_verification' );

			Route::get( 'self/receipt/upload/{id?}', 'UserController@multi_upload' )->name( 'users.multi_upload' );
			Route::post( 'self/receipt/upload', 'UserController@store_multi_upload' )->name( 'users.store_multi_upload' );
 
			Route::get( 'self/change-password', 'UserController@change_password' )->name( 'users.change_password' );
			Route::post( 'self/change-password', 'UserController@store_password' )->name( 'users.store_password' );

			Route::get( 'self/upload/success', 'UserController@page_success_upload' )->name( 'users.page_success_upload' );

			/**
			 * all address member
			 */
			Route::get( 'self/address', 'UserController@address_page' )->name( 'users.address_page' );
			Route::get( 'self/address/default/{id}', 'UserController@address_default_store' )->name( 'users.address_default_store' );

			Route::get( 'self/address/edit/{id?}', 'UserController@address_edit_page' )->name( 'users.address_edit' );
			Route::post( 'self/address/edit/{id?}', 'UserController@address_store' )->name( 'users.address_store' );

			Route::get( 'self/address/delete/{id?}', 'UserController@address_delete' )->name( 'users.address_delete' );

			/*
				upload data
			 */
			Route::post( 'members/upload/photo', 'UserController@photo_upload' )->name( 'users.photo_upload' );
			Route::post( 'members/upload/receipt/{id}', 'UserController@receipt_upload' )->name( 'users.receipt_upload' );


            /**
             * promo codes - after login
             */
            Route::get( 'promo-codes/participate/{id}', 'PromoCodeController@participate' )->name( 'promo_codes.participate' );
            Route::post( 'promo-codes/participate/{id}', 'PromoCodeController@participate' )->name( 'promo_codes.participate' );

			Route::get( 'promo-codes/downloads/{id}', 'PromoCodeController@download_file' )->name( 'promo_codes.download' );

            /**
             * promo codes - for type B with form and receipt upload
             */
			Route::get( 'self/promo-codes/list', 'UserController@promo_code_list' )->name( 'users.promo_code_list' );


				/**
				 * success page
				 */
				Route::get( 'self/promo-codes/redeem/success', 'PromoCodeController@success_redeem' )->name( 'promo_codes.success_redeem' );
	            Route::get( 'self/promo-codes/upload/success', 'PromoCodeController@success_upload' )->name( 'promo_codes.success_upload' );

	            /**
	             * store redeem
	             */
				Route::get( 'self/promo-codes/redeem/{id}', 'PromoCodeController@store_redeem' )->name( 'promo_codes.store_redeem' );

	            /**
	             * upload page
	             */
	            Route::get( 'self/promo-codes/upload/{id?}', 'PromoCodeController@multi_upload' )->name( 'promo_codes.multi_upload' );
	            Route::post( 'self/promo-codes/upload', 'PromoCodeController@store_multi_upload' )->name( 'promo_codes.store_multi_upload' );


	            Route::get( 'self/promo-codes/receipts/{id}', 'UserController@promo_codes_receipt_list' )->name( 'users.promo_codes_receipt_list' );
				Route::post( 'self/promo-codes/delete', 'UserController@promo_code_delete_participation' )->name( 'users.promo_code_delete_participation' );

			/**
			 * lucky draw subscribe & participation
			 */
			Route::get( 'lucky-draws/participate/{id}', 'LuckyDrawController@participation' )->name( 'lucky.participation' );
			Route::post( 'lucky-draws/subscribe/{id}', 'LuckyDrawController@subscribe_member' )->name( 'lucky.subscribe' );
            Route::get( 'lucky-draws/receipts/{lucky_draw_id}', 'LuckyDrawController@receipt_list' )->name( 'lucky.receipts' );

            /**
             * redemption participation
             */

			Route::get( 'redemptions/participate/{id}', 'RedemptionController@participate' )->name( 'redemptions.participate' );
			Route::post( 'redemptions/participate/{id}', 'RedemptionController@participate' )->name( 'redemptions.participate' );


			Route::get( 'self/redemptions/summary', 'UserController@redemptions_summary' )->name( 'users.redemptions_summary' );
			Route::get( 'self/promo-codes/summary', 'UserController@promo_codes_summary' )->name( 'users.promo_codes_summary' );
			Route::get( 'self/free-samples/summary', 'UserController@free_samples_summary' )->name( 'users.free_samples_summary' );

			/**
			 * redemption - success
			 */
			Route::get( 'self/redemptions/redeem/success', 'RedemptionController@success_redeem' )->name( 'redemptions.success_redeem' );
			Route::get( 'self/redemptions/redeem/{id}', 'RedemptionController@store_redeem' )->name( 'redemptions.store_redeem' );

			Route::get( 'self/redemptions/upload/success', 'RedemptionController@success_upload' )->name( 'redemptions.success_upload' );


			Route::get( 'self/redemptions/upload/{id?}', 'RedemptionController@multi_upload' )->name( 'redemptions.multi_upload' );
			Route::post( 'self/redemptions/upload', 'RedemptionController@store_multi_upload' )->name( 'redemptions.store_multi_upload' );

            Route::get( 'self/redemptions/receipts/{id}', 'RedemptionController@receipt_list' )->name( 'users.redemption_receipt_list' );


			Route::post( 'self/redemptions/delete', 'UserController@redemption_delete_participation' )->name( 'users.redemption_delete_participation' );


			/**
			 * free sample participation
			 */
			// Route::get( 'redemptions/participate/{id}', 'RedemptionController@participate' )->name( 'redemptions.participate' );
			Route::post( 'free-samples/participate/{id}', 'FreeSampleController@participate' )->name( 'free_samples.participate' );

			Route::post( 'free-samples/request/select-store/{id}', 'FreeSampleController@request_select_store' )->name( 'free_samples.request_select_store' );
			Route::post( 'free-samples/request/new-store/{id}', 'FreeSampleController@request_new_store' )->name( 'free_samples.request_new_store' );

			Route::get( 'free-samples/request/success', 'FreeSampleController@request_success_page' )->name( 'free_samples.request_success' );

			Route::get( 'free-samples/request/{id}', 'FreeSampleController@request_page' )->name( 'free_samples.request' );


            Route::get( 'self/free-samples/request/{id}', 'UserController@free_sample_request_list' )->name( 'users.free_samples_request_list' );


		});

		Route::get( 'forget-password', 'AuthController@forget_password' )->name( 'auth.forget_password' );
		Route::post( 'forget-password', 'AuthController@mail_forget_password' )->name( 'auth.mail_forget_password' );
		Route::post( 'reset-password', 'AuthController@reset_password' )->name( 'auth.reset_password' );

		Route::get( 'success-password', 'AuthController@success_password' )->name( 'auth.success_password' );

		Route::get( 'qr', 'ContestController@qr' )->name( 'contests.qr' );

		/**
		 * CONTESTS
		 */
		Route::get( 'contests', 'ContestController@index' )->name( 'contests.index' );

		/**
		 * CATEGORIES
		 */
		Route::get( 'categories', 'CategoryController@index' )->name( 'categories.index' );

app/Http/Controllers/Front/Heng/API/EmailController.php
<?php

namespace App\Http\Controllers\Front\Heng\API;

use App\Http\Controllers\APIController;
use App\Models\MailSubscriber;
use App\Models\Verification;

class EmailController extends APIController
{
    public function subscribeNewsletter()
    {
        $authed_user    = \Auth::user();

        $rules =
        [
            'email'      => 'required|email|unique:heng_db_mail_subscribers,email'
        ];

        $validate = $this->validate( $this->r, $rules );

        if( $validate !== true )
        {
            return $this->output( $validate, false);
        }

        extract( $this->r->all() );

        // $r                      = new MailSubscriber;
        // $r->email               = $email;
        // $r->save();

        $db_verification     = Verification::createRecord( $email, null, 'newsletter' );

        $db_verification->sendNewsletterEmail( $db_verification );

        $msg = 'Thank you for susbcribing. A verification email has been sent to your email.';

        return $this->output( $msg, true );
    }
}

app/Http/Controllers/Front/Heng/API/SearchController.php
<?php

namespace App\Http\Controllers\Front\Heng\API;

use App\Http\Controllers\APIController;

use App\Models\LuckyDraw;
use App\Models\Promotion;
use App\Models\Brand;
use App\Models\Retailer;
use App\Models\FreeSample;

class SearchController extends APIController
{
    public function indexLuckyDraws()
    {
        $query = $this->r->get( 'q' );

        $db_contest = LuckyDraw::published()->where( 'name', 'LIKE', '%'.$query.'%' )->get();

        $data = [];

        foreach( $db_contest as $dc )
        {
            $temp = [
                'id' => $dc->id,
                'label' => $dc->name,
                'url' => $dc->detailUrl()
            ];

            $data[] = $temp;
        } 

        return $this->output( $data );
    }

    public function indexFreeSamples()
    {
        $query = $this->r->get( 'q' );

        $db_contest = FreeSample::published()->where( 'name', 'LIKE', '%'.$query.'%' )->get();

        $data = [];

        foreach( $db_contest as $dc )
        {
            $temp = [
                'id' => $dc->id,
                'label' => $dc->name,
                'url' => $dc->detailUrl()
            ];

            $data[] = $temp;
        } 

        return $this->output( $data );
    }

    public function indexRedemptions()
    {
        $query = $this->r->get( 'q' );

        $db_contest = Promotion::published()->categoryRedemption()->where( 'name', 'LIKE', '%'.$query.'%' )->get();

        $data = [];

        foreach( $db_contest as $dc )
        {
            $temp = [
                'id' => $dc->id,
                'label' => $dc->name,
                'url' => $dc->urlRedemption()
            ];

            $data[] = $temp;
        } 

        return $this->output( $data );
    }

    public function indexFreeGifts()
    {
        $query = $this->r->get( 'q' );

        $db_contest = Promotion::published()->categoryGift()->where( 'name', 'LIKE', '%'.$query.'%' )->get();

        $data = [];

        foreach( $db_contest as $dc )
        {
            $temp = [
                'id' => $dc->id,
                'label' => $dc->name,
                'url' => $dc->urlGift()
            ];

            $data[] = $temp;
        } 

        return $this->output( $data );
    }

    public function indexBrands()
    {
        $query = $this->r->get( 'q' );

        $db_contest = Brand::published()->featured()->where( 'name', 'LIKE', '%'.$query.'%' )->get();

        $data = [];

        foreach( $db_contest as $dc )
        {
            $temp = [
                'id' => $dc->id,
                'label' => $dc->name,
                'url' => $dc->searchUrl()
            ];

            $data[] = $temp;
        } 

        return $this->output( $data );
    }

    public function indexRetailers()
    {
        $query = $this->r->get( 'q' );

        $db_contest = Retailer::published()->where( 'name', 'LIKE', '%'.$query.'%' )->get();

        $data = [];

        foreach( $db_contest as $dc )
        {
            $temp = [
                'id' => $dc->id,
                'label' => $dc->name,
                'url' => $dc->searchUrl()
            ];

            $data[] = $temp;
        } 

        return $this->output( $data );
    }

}

app/Http/Controllers/Front/Heng/API/SelfController.php
<?php

namespace App\Http\Controllers\Front\Heng\API;

use App\Models\Favorite;
use App\Models\Brand;
use App\Http\Controllers\APIController;

class SelfController extends APIController
{
    public function toggleFavorite()
    {
        $user = \Auth::user();
        $id   = $this->r->get( 'id' );

        $current = Favorite::forBrand()
                            ->whereModelId( $id )
                            ->whereMemberId( $user->id )
                            ->first();

        $subscribed = true;


        /**
         * get brand data for favorite count
         */
        $db_brand = Brand::find( $id );

        if( $current )
        {
            $current->delete();
            $subscribed = false;

            /**
             * decrease favorite
             */
            $db_brand->total_favorite -= 1;
            $db_brand->save();
        }
        else
        {
            $new = new Favorite;
            $new->member_id  = $user->id;
            $new->model_id   = $id;
            $new->model_type = Brand::class;
            $new->save();

            /**
             * increase favorite
             */
            $db_brand->total_favorite += 1;
            $db_brand->save();
        }

        $data = [
            'subscribed' => $subscribed
        ];

        return $this->output( $data );
    }
}

app/Http/Controllers/Front/Heng/BaseController.php
<?php

namespace App\Http\Controllers\Front\Heng;

use App\Http\Controllers\BlankController;
use Illuminate\Http\Request;

use App\Models\Announcement;
use App\Models\Information;
use App\Models\Setting;
use App\Models\Brand;
use App\Models\Retailer;
use Artesaos\SEOTools\Traits\SEOTools as SEOToolsTrait;

class BaseController extends BlankController
{
	use SEOToolsTrait;

	public function __construct( Request $r )
	{
		parent::__construct( $r );
	}

    protected function generateMetaSEO()
    {
        $this->seo()->opengraph()->setUrl(url()->current());
    }

	protected function beforeOutput()
	{
        $this->generateMetaSEO();

		$st_setting 			= Setting::first();
		$st_footer_information 	= Information::published()->showFooter()->orderBy( 'sort_order', 'asc' )->take(8)->get();

		$st_footer_brands  		= Brand::published()->featured()->orderBy( 'sort_order', 'asc' )->take(8)->get();
		$st_footer_retailers 	= Retailer::published()->orderBy( 'created_at', 'desc' )->take(8)->get();

		$st_announcements 		= Announcement::published()->orderBy( 'created_at', 'desc' )->take(5)->get();

		return [
			'authed_user' 	 		=> \Auth::user(),
			'st_setting' 	 		=> $st_setting,
			'st_footer_brands' 		=> $st_footer_brands,
			'st_footer_retailers' 	=> $st_footer_retailers,
			'st_footer_info' 		=> $st_footer_information,
			'st_announcements' 		=> $st_announcements
		];
	}

}

app/Http/Controllers/Front/Heng/CategoryController.php
<?php

namespace App\Http\Controllers\Front\Heng;

class CategoryController extends BaseController
{
	public function index()
	{

		$data = compact( '' );
		return $this->output( 'f.heng.categories.index', $data );
	}
}

app/Http/Controllers/Front/Heng/QRController.php
<?php

namespace App\Http\Controllers\Front\Heng;

class QRController extends BaseController
{
	public function index()
	{
		$data = [];
		return $this->output( 'f.heng.scan-qr.index', $data );
	}
}

resources/views/f/heng/redemptions/article_detail.blade.php
@extends('f.heng.base')

@section( 'head_page_css' )
    @parent

    {!! html_css( 'heng/redemption-detail.css' ) !!}

    {!! html_css( 'owl.carousel/dist/assets/owl.carousel.min.css', 'js/vendors' ) !!}
    {!! html_css( 'owl.carousel/dist/assets/owl.theme.default.min.css', 'js/vendors' ) !!}

@stop

@section( 'page_content' )

<section class="st-container with-margin">

    <section class="split-layout">

        <div class="sl-left">

            <!-- information -->
            @include( 'f.heng._partials._section_tab_layout' )

            <!-- retailer contest -->
            @include( 'f.heng._partials._retailer_associates' )
            
            <!-- social network sharing -->
            @include( 'f.heng._partials._share_social_networks' )

        </div>

    </section>

    @include( 'f.heng._partials._section_owl_other_items', 
        [ 'owl_redirect_var'=> 'redemption',
          'owl_other_title_name' => 'Other Redemptions', 
          'owl_overlayed' => false,
          'owl_other_webview'=> true ] )

</section>


@stop

@section( 'footer_content' )
    @include( 'f.heng.layouts._footer' )
@stop


@section( 'foot_page_js' )
    @parent
    {!! html_js( 'js/vendors/owl.carousel/dist/owl.carousel.min.js' ) !!}
    {!! html_js( 'js/f/mobile-owl-carousel.js' ) !!}

    <script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-5b73f77d0c8e5f78" async="async"></script>
@stop

resources/views/f/heng/redemptions/old_article_detail.blade.php
@extends('f.heng.base')

@section( 'head_page_css' )
    @parent

    {!! html_css( 'heng/redemption-detail.css' ) !!}

    {!! html_css( 'owl.carousel/dist/assets/owl.carousel.min.css', 'js/vendors' ) !!}
    {!! html_css( 'owl.carousel/dist/assets/owl.theme.default.min.css', 'js/vendors' ) !!}

@stop

@section( 'page_content' )

<section class="st-container with-margin">

    <section class="split-layout">

        <div class="sl-left">

            <!-- information -->
            @include( 'f.heng._partials._section_tab_layout' )

            <!-- retailer contest -->
            @include( 'f.heng._partials._retailer_associates' )
            
            <!-- social network sharing -->
            @include( 'f.heng._partials._share_social_networks' )

        </div>

        <div class="sl-right">
            <section class="ct-ondesktop">
                @include( 'f.heng._partials._sidebar_other_items', 
                ['other_sidebar_title' => 'Other Redemptions',
                'other_sidebar_var'    => 'redemption'
                ] )
            </section>
        </div>

    </section>

    @include( 'f.heng._partials._section_owl_other_items', 
        [ 'owl_redirect_var'=> 'redemption',
          'owl_other_title_name' => 'Other Redemptions', 
          'owl_overlayed' => false,
          'owl_other_webview'=> false ] )

</section>


@stop

@section( 'footer_content' )
    @include( 'f.heng.layouts._footer' )
@stop


@section( 'foot_page_js' )
    @parent
    {!! html_js( 'js/vendors/owl.carousel/dist/owl.carousel.min.js' ) !!}
    {!! html_js( 'js/f/mobile-owl-carousel.js' ) !!}

    <script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-5b73f77d0c8e5f78" async="async"></script>
@stop

resources/views/f/heng/redemptions/page_success_redeem.blade.php
@extends('f.heng.base')

@section( 'head_page_css' )
	@parent

	{!! html_css( 'heng/self-upload-success.css' ) !!}
@stop

@section( 'low_padding_body', 'st-lower' )

@section( 'page_content' )

<section class="st-container with-margin">

	<div id="content_paragraph">
		<p class="title">
			Well Done! 
		</p>
		<p class="text">
			Look out for the gift redemption details via email as soon as we verify your receipts.
		</p>
		<p class="text">
		</p>

		<a href="{{ route( 'f.heng.home' ) }}" class="button-redirect">OK</a>
	</div>

</section>

@stop

@section( 'footer_content' )
	@include( 'f.heng.layouts._footer_min' )
@stop

resources/views/f/heng/redemptions/page_success_upload.blade.php
@extends('f.heng.base')

@section( 'head_page_css' )
	@parent

	{!! html_css( 'heng/self-upload-success.css' ) !!}
@stop

@section( 'low_padding_body', 'st-lower' )

@section( 'page_content' )

<section class="st-container with-margin">

	<div id="content_paragraph">
		<p class="title">
			Well Done! 
		</p>
		<p class="text">
			Your participation is successful. Please remember to click the "Redeem Now" button when you have qualified.
		</p>
		<p class="text">
		</p>

		<a href="{{ route( 'f.heng.home' ) }}" class="button-redirect">OK</a>
	</div>

</section>

@stop

@section( 'footer_content' )
	@include( 'f.heng.layouts._footer_min' )
@stop

resources/views/f/heng/redemptions/participate_detail.blade.php
@extends('f.heng.base')

@section( 'head_page_css' )
	@parent
	{!! html_css( 'heng/redemption-detail.css' ) !!}

	{!! html_css( 'owl.carousel/dist/assets/owl.carousel.min.css', 'js/vendors' ) !!}
	{!! html_css( 'owl.carousel/dist/assets/owl.theme.default.min.css', 'js/vendors' ) !!}

@stop

@section( 'page_content' )

<section class="st-container with-margin">

    @if( html_message_is_valid() )
        <div class="ct-error-info show-panel pad-bottom {{ html_add_error_class( 'txt-error', 'txt-valid' ) }}">
            {{ html_get_first_message() }}
        </div>
    @endif

	<section class="split-layout">

		<div class="sl-left">

            <!-- information -->
            @include( 'f.heng._partials._section_tab_layout' )

			<!-- retailer contest -->
			@include( 'f.heng._partials._retailer_associates' )
            
            <!-- social network sharing -->
            @include( 'f.heng._partials._share_social_networks' )

		</div>

		<div class="sl-right">

			@if( $db_exist_participation )

				@include( 'f.heng._partials._panel_more_data', 
				[ 'panel_more_title' => 'More Redemptions', 
				'panel_more_paragraph' => 'You can upload receipts until you qualify for redemption. Browse our other redemptions.',
				'panel_more_redirect' => route( 'f.heng.redemptions.index' ),
				'panel_more_btn' => 'Browse Redemptions'
				 ] )

			@endif

			<div class="panel-container">
				<!-- Main title text -->
				<div class="fd-main-title">
					{{ $display_info['main_title'] }}
				</div>

				@if( $log_user )

					@if( !html_message_is_valid() )
					<!-- error info -->
					<div class="ct-error-info {{ html_add_error_class() }}">
				    	{{ html_get_first_error_message() }}
					</div>
					@endif

					@if( $db_exist_participation && !$db_active_participation && !$db->isDateExpired() )
						<a href="{{ route( 'f.heng.redemptions.participate',  $db->id ) }}" class="fd-button red">
							Participate Again
						</a>
					@elseif( $db_active_participation && !$db->isDateExpired() )
						<a href="{{ route( 'f.heng.redemptions.multi_upload', [ null, 's' => $db_active_participation->id ]) }}" class="fd-button red">
							Upload Receipt
						</a>
					@endif

					{!! form_open_post( route( 'f.heng.redemptions.participate', $db->id ), [ 'id'=>'form_receipt' ], true ) !!}
					@if( !$authed_user->isProfilePartialFilled() && !$db->isDateExpired() )

						@include( 'f.heng._partials._form_member_data' )
					
					@endif

					@if( !$db_exist_participation && !$db->isDateExpired() )
					<!-- checkbox agreement -->
					<div class="cf-agreement">
						<input type="checkbox" name="check_agreement" id="check-agreement" class="css-checkbox" value="YES" @if( old('check_agreement') == 'YES')checked="checked"@endif />
						<label for="check-agreement" class="css-label">
							By participating, you are agreeing to this redemption’s terms & conditions.
						</label>
					</div>
					@endif

					<!-- note -->
					@if( $db->isDateExpired() )
						<div class="fd-guide">
							Sorry, our redemption period has ended.
						</div>
					@elseif( $db_active_participation )
						<div class="fd-guide">
							Note: <br/>
							You can choose multiple redemptions for a receipt<br/>
							JPG, JPEG, PNG file only
						</div>
					@elseif( !$db_exist_participation && !$authed_user->isProfilePartialFilled() )
						<div class="fd-guide agreement">
							To participate in this redemption, you must fill all the information.
						</div>
					@endif

					@if( !$db_exist_participation && !$db->isDateExpired() )
					<!-- submit button -->
						<div>
							<input type="submit" class="fd-button" value="Participate">
						</div>
					@endif
					{!! form_close() !!}

					@if( $receipt_count > 0 )
						<!-- url file -->
						<div class="ct-uploaded-receipt-files mobile receipt-count">
                            You have submitted {{ $receipt_count }} {{ str_plural( 'receipt', $receipt_count )}}
                            <a href="{{ $db_active_participation->receiptListUrl() }}" class="txt-link">view all receipts</a>
                        </div>
					@endif

				@else
					<!-- redirect login page -->
					<a href="{{ route( 'f.heng.auth.login', [ 'l' => encode_authenticate_redirect( $db->urlRedemption()) ] ) }}" class="fd-button">Login to Participate</a>
					<div class="fd-guide">
						Note: <br/>
						You can upload multiple receipts<br/>
						You can participate first and upload receipt afterwards<br/>
						JPG, JPEG, PNG file only
					</div>
				@endif

			</div>
			@if( $receipt_count > 0 )

				@include( 'f.heng._partials._panel_more_data', 
				[ 'panel_more_title' => 'Get Your Redemption!', 
				'panel_more_paragraph' => 'Already qualified for redemption? Request for redemption now.',
				'panel_more_redirect' => route( 'f.heng.redemptions.store_redeem', $db_active_participation->id ),
				'panel_more_btn' => 'Redeem Now',
				'panel_box_css' => 'm-top'
				 ] )

				<!-- url file -->
				<div class="ct-uploaded-receipt-files shift-right receipt-count">
                    You have submitted {{ $receipt_count }} {{ str_plural( 'receipt', $receipt_count )}}
                    <a href="{{ $db_active_participation->receiptListUrl() }}" class="txt-link">view all receipts</a>
				</div>
			@endif
		</div>
	</section>

    @include( 'f.heng._partials._section_owl_other_items', 
        [ 'owl_redirect_var'=> 'redemption',
          'owl_other_title_name' => 'Other Redemptions', 
          'owl_overlayed' => false,
          'owl_other_webview'=> true ] )

</section>

@stop

@section( 'footer_content' )
	@include( 'f.heng.layouts._footer' )
@stop

@section( 'foot_page_js' )
	@parent
	{!! html_js( 'js/vendors/owl.carousel/dist/owl.carousel.min.js' ) !!}
	{!! html_js( 'js/f/mobile-owl-carousel.js' ) !!}

	<script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-5b73f77d0c8e5f78" async="async"></script>
@stop