routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(
	[
		'namespace' => 'Front\Heng',
		'as' 		=> 'f.heng.',
	],
	function() {
		Route::get('/', 'HomeController@index' )->name('home');

		/*
			email verification link url
		 */
		Route::get( 'verify/member/{token}', [ 'as' => 'user.verify_member', 'uses' => 'UserController@verify_member' ]);
		Route::get( 'verify/newsletter/{token}', [ 'as' => 'user.verify_newsletter', 'uses' => 'UserController@verify_subscriber' ]);
		Route::get( 'verify/forgot-password/{token}', [ 'as' => 'user.verify_forgot_password', 'uses' => 'AuthController@verify_forgot_password' ]);

		Route::group(
			[
				'middleware' => [ 'auth.frontend.guest' ]
			],
		function()
		{
			/**
			 * AUTH
			 */
			Route::get( 'register', 'AuthController@register' )->name( 'auth.register' );
			Route::post( 'register', 'AuthController@store_register' )->name( 'auth.store_register' );

			/**
			 * request new verification
			 */
			Route::get( 'request/verification/{email?}', 'AuthController@request_verification' )->name( 'auth.request_verification' );


			Route::get( 'login', 'AuthController@login' )->name( 'auth.login' );
			Route::post( 'login', 'AuthController@auth' )->name( 'auth.auth' );

			Route::get( 'login/facebook', 'AuthController@login_facebook' )->name( 'auth.login_facebook' );

		});

		Route::group(
			[
				'middleware' => [ 'auth.frontend' ]
			],
		function()
		{
			/**
			 * AUTH
			 */
			Route::get( 'logout', 'AuthController@logout' )->name( 'auth.logout' );

			Route::get( 'update-password', 'AuthController@update_password' )->name( 'auth.update_password' );
			Route::get( 'success-password', 'AuthController@success_password' )->name( 'auth.success_password' );

			/**
			 * SELF - USER
			 */
			Route::get( 'self/dashboard', 'UserController@dashboard' )->name( 'users.dashboard' );
			Route::get( 'self/list/redemptions', 'UserController@redemption_list' )->name( 'users.redemption_list' );

			Route::get( 'self/delete/contest/{id}', 'UserController@delete_contest' )->name( 'users.delete_contest' );
			Route::get( 'self/contest/{status}', 'UserController@list_contests' )->name( 'users.list_contests' );

			Route::post( 'self/delete/contest', 'UserController@multi_delete_contest' )->name( 'users.multi_delete_contest' );

			Route::get( 'self/contest-summary', 'UserController@contest_summary' )->name( 'users.contest_summary' );

			Route::get( 'self/my-account', 'UserController@my_account' )->name( 'users.my_account' );
			Route::post( 'self/my-account', 'UserController@store_profile' )->name( 'users.my_account' );

			Route::get( 'self/resend/verification', 'UserController@resend_verification' )->name( 'users.resend_verification' );

			Route::get( 'self/receipt/upload/{id?}', 'UserController@multi_upload' )->name( 'users.multi_upload' );
			Route::post( 'self/receipt/upload', 'UserController@store_multi_upload' )->name( 'users.store_multi_upload' );
 
			Route::get( 'self/change-password', 'UserController@change_password' )->name( 'users.change_password' );
			Route::post( 'self/change-password', 'UserController@store_password' )->name( 'users.store_password' );

			Route::get( 'self/upload/success', 'UserController@page_success_upload' )->name( 'users.page_success_upload' );

			/**
			 * all address member
			 */
			Route::get( 'self/address', 'UserController@address_page' )->name( 'users.address_page' );
			Route::get( 'self/address/default/{id}', 'UserController@address_default_store' )->name( 'users.address_default_store' );

			Route::get( 'self/address/edit/{id?}', 'UserController@address_edit_page' )->name( 'users.address_edit' );
			Route::post( 'self/address/edit/{id?}', 'UserController@address_store' )->name( 'users.address_store' );

			Route::get( 'self/address/delete/{id?}', 'UserController@address_delete' )->name( 'users.address_delete' );

			/*
				upload data
			 */
			Route::post( 'members/upload/photo', 'UserController@photo_upload' )->name( 'users.photo_upload' );
			Route::post( 'members/upload/receipt/{id}', 'UserController@receipt_upload' )->name( 'users.receipt_upload' );


            /**
             * promo codes - after login
             */
            Route::get( 'promo-codes/participate/{id}', 'PromoCodeController@participate' )->name( 'promo_codes.participate' );
            Route::post( 'promo-codes/participate/{id}', 'PromoCodeController@participate' )->name( 'promo_codes.participate' );

			Route::get( 'promo-codes/downloads/{id}', 'PromoCodeController@download_file' )->name( 'promo_codes.download' );

            /**
             * promo codes - for type B with form and receipt upload
             */
			Route::get( 'self/promo-codes/list', 'UserController@promo_code_list' )->name( 'users.promo_code_list' );


				/**
				 * success page
				 */
				Route::get( 'self/promo-codes/redeem/success', 'PromoCodeController@success_redeem' )->name( 'promo_codes.success_redeem' );
	            Route::get( 'self/promo-codes/upload/success', 'PromoCodeController@success_upload' )->name( 'promo_codes.success_upload' );

	            /**
	             * store redeem
	             */
				Route::get( 'self/promo-codes/redeem/{id}', 'PromoCodeController@store_redeem' )->name( 'promo_codes.store_redeem' );

	            /**
	             * upload page
	             */
	            Route::get( 'self/promo-codes/upload/{id?}', 'PromoCodeController@multi_upload' )->name( 'promo_codes.multi_upload' );
	            Route::post( 'self/promo-codes/upload', 'PromoCodeController@store_multi_upload' )->name( 'promo_codes.store_multi_upload' );


	            Route::get( 'self/promo-codes/receipts/{id}', 'UserController@promo_codes_receipt_list' )->name( 'users.promo_codes_receipt_list' );
				Route::post( 'self/promo-codes/delete', 'UserController@promo_code_delete_participation' )->name( 'users.promo_code_delete_participation' );

			/**
			 * lucky draw subscribe & participation
			 */
			Route::get( 'lucky-draws/participate/{id}', 'LuckyDrawController@participation' )->name( 'lucky.participation' );
			Route::post( 'lucky-draws/subscribe/{id}', 'LuckyDrawController@subscribe_member' )->name( 'lucky.subscribe' );
            Route::get( 'lucky-draws/receipts/{lucky_draw_id}', 'LuckyDrawController@receipt_list' )->name( 'lucky.receipts' );

            /**
             * redemption participation
             */

			Route::get( 'redemptions/participate/{id}', 'RedemptionController@participate' )->name( 'redemptions.participate' );
			Route::post( 'redemptions/participate/{id}', 'RedemptionController@participate' )->name( 'redemptions.participate' );


			Route::get( 'self/redemptions/summary', 'UserController@redemptions_summary' )->name( 'users.redemptions_summary' );
			Route::get( 'self/promo-codes/summary', 'UserController@promo_codes_summary' )->name( 'users.promo_codes_summary' );
			Route::get( 'self/free-samples/summary', 'UserController@free_samples_summary' )->name( 'users.free_samples_summary' );

			/**
			 * redemption - success
			 */
			Route::get( 'self/redemptions/redeem/success', 'RedemptionController@success_redeem' )->name( 'redemptions.success_redeem' );
			Route::get( 'self/redemptions/redeem/{id}', 'RedemptionController@store_redeem' )->name( 'redemptions.store_redeem' );

			Route::get( 'self/redemptions/upload/success', 'RedemptionController@success_upload' )->name( 'redemptions.success_upload' );


			Route::get( 'self/redemptions/upload/{id?}', 'RedemptionController@multi_upload' )->name( 'redemptions.multi_upload' );
			Route::post( 'self/redemptions/upload', 'RedemptionController@store_multi_upload' )->name( 'redemptions.store_multi_upload' );

            Route::get( 'self/redemptions/receipts/{id}', 'RedemptionController@receipt_list' )->name( 'users.redemption_receipt_list' );


			Route::post( 'self/redemptions/delete', 'UserController@redemption_delete_participation' )->name( 'users.redemption_delete_participation' );


			/**
			 * free sample participation
			 */
			// Route::get( 'redemptions/participate/{id}', 'RedemptionController@participate' )->name( 'redemptions.participate' );
			Route::post( 'free-samples/participate/{id}', 'FreeSampleController@participate' )->name( 'free_samples.participate' );

			Route::post( 'free-samples/request/select-store/{id}', 'FreeSampleController@request_select_store' )->name( 'free_samples.request_select_store' );
			Route::post( 'free-samples/request/new-store/{id}', 'FreeSampleController@request_new_store' )->name( 'free_samples.request_new_store' );

			Route::get( 'free-samples/request/success', 'FreeSampleController@request_success_page' )->name( 'free_samples.request_success' );

			Route::get( 'free-samples/request/{id}', 'FreeSampleController@request_page' )->name( 'free_samples.request' );


            Route::get( 'self/free-samples/request/{id}', 'UserController@free_sample_request_list' )->name( 'users.free_samples_request_list' );


		});

		Route::get( 'forget-password', 'AuthController@forget_password' )->name( 'auth.forget_password' );
		Route::post( 'forget-password', 'AuthController@mail_forget_password' )->name( 'auth.mail_forget_password' );
		Route::post( 'reset-password', 'AuthController@reset_password' )->name( 'auth.reset_password' );

		Route::get( 'success-password', 'AuthController@success_password' )->name( 'auth.success_password' );

		Route::get( 'qr', 'ContestController@qr' )->name( 'contests.qr' );

		/**
		 * CONTESTS
		 */
		Route::get( 'contests', 'ContestController@index' )->name( 'contests.index' );

		/**
		 * CATEGORIES
		 */
		Route::get( 'categories', 'CategoryController@index' )->name( 'categories.index' );

app/Http/Controllers/Front/Heng/API/EmailController.php
<?php

namespace App\Http\Controllers\Front\Heng\API;

use App\Http\Controllers\APIController;
use App\Models\MailSubscriber;
use App\Models\Verification;

class EmailController extends APIController
{
    public function subscribeNewsletter()
    {
        $authed_user    = \Auth::user();

        $rules =
        [
            'email'      => 'required|email|unique:heng_db_mail_subscribers,email'
        ];

        $validate = $this->validate( $this->r, $rules );

        if( $validate !== true )
        {
            return $this->output( $validate, false);
        }

        extract( $this->r->all() );

        // $r                      = new MailSubscriber;
        // $r->email               = $email;
        // $r->save();

        $db_verification     = Verification::createRecord( $email, null, 'newsletter' );

        $db_verification->sendNewsletterEmail( $db_verification );

        $msg = 'Thank you for susbcribing. A verification email has been sent to your email.';

        return $this->output( $msg, true );
    }
}

app/Http/Controllers/Front/Heng/API/SearchController.php
<?php

namespace App\Http\Controllers\Front\Heng\API;

use App\Http\Controllers\APIController;

use App\Models\LuckyDraw;
use App\Models\Promotion;
use App\Models\Brand;
use App\Models\Retailer;
use App\Models\FreeSample;

class SearchController extends APIController
{
    public function indexLuckyDraws()
    {
        $query = $this->r->get( 'q' );

        $db_contest = LuckyDraw::published()->where( 'name', 'LIKE', '%'.$query.'%' )->get();

        $data = [];

        foreach( $db_contest as $dc )
        {
            $temp = [
                'id' => $dc->id,
                'label' => $dc->name,
                'url' => $dc->detailUrl()
            ];

            $data[] = $temp;
        } 

        return $this->output( $data );
    }

    public function indexFreeSamples()
    {
        $query = $this->r->get( 'q' );

        $db_contest = FreeSample::published()->where( 'name', 'LIKE', '%'.$query.'%' )->get();

        $data = [];

        foreach( $db_contest as $dc )
        {
            $temp = [
                'id' => $dc->id,
                'label' => $dc->name,
                'url' => $dc->detailUrl()
            ];

            $data[] = $temp;
        } 

        return $this->output( $data );
    }

    public function indexRedemptions()
    {
        $query = $this->r->get( 'q' );

        $db_contest = Promotion::published()->categoryRedemption()->where( 'name', 'LIKE', '%'.$query.'%' )->get();

        $data = [];

        foreach( $db_contest as $dc )
        {
            $temp = [
                'id' => $dc->id,
                'label' => $dc->name,
                'url' => $dc->urlRedemption()
            ];

            $data[] = $temp;
        } 

        return $this->output( $data );
    }

    public function indexFreeGifts()
    {
        $query = $this->r->get( 'q' );

        $db_contest = Promotion::published()->categoryGift()->where( 'name', 'LIKE', '%'.$query.'%' )->get();

        $data = [];

        foreach( $db_contest as $dc )
        {
            $temp = [
                'id' => $dc->id,
                'label' => $dc->name,
                'url' => $dc->urlGift()
            ];

            $data[] = $temp;
        } 

        return $this->output( $data );
    }

    public function indexBrands()
    {
        $query = $this->r->get( 'q' );

        $db_contest = Brand::published()->featured()->where( 'name', 'LIKE', '%'.$query.'%' )->get();

        $data = [];

        foreach( $db_contest as $dc )
        {
            $temp = [
                'id' => $dc->id,
                'label' => $dc->name,
                'url' => $dc->searchUrl()
            ];

            $data[] = $temp;
        } 

        return $this->output( $data );
    }

    public function indexRetailers()
    {
        $query = $this->r->get( 'q' );

        $db_contest = Retailer::published()->where( 'name', 'LIKE', '%'.$query.'%' )->get();

        $data = [];

        foreach( $db_contest as $dc )
        {
            $temp = [
                'id' => $dc->id,
                'label' => $dc->name,
                'url' => $dc->searchUrl()
            ];

            $data[] = $temp;
        } 

        return $this->output( $data );
    }

}

app/Http/Controllers/Front/Heng/API/SelfController.php
<?php

namespace App\Http\Controllers\Front\Heng\API;

use App\Models\Favorite;
use App\Models\Brand;
use App\Http\Controllers\APIController;

class SelfController extends APIController
{
    public function toggleFavorite()
    {
        $user = \Auth::user();
        $id   = $this->r->get( 'id' );

        $current = Favorite::forBrand()
                            ->whereModelId( $id )
                            ->whereMemberId( $user->id )
                            ->first();

        $subscribed = true;


        /**
         * get brand data for favorite count
         */
        $db_brand = Brand::find( $id );

        if( $current )
        {
            $current->delete();
            $subscribed = false;

            /**
             * decrease favorite
             */
            $db_brand->total_favorite -= 1;
            $db_brand->save();
        }
        else
        {
            $new = new Favorite;
            $new->member_id  = $user->id;
            $new->model_id   = $id;
            $new->model_type = Brand::class;
            $new->save();

            /**
             * increase favorite
             */
            $db_brand->total_favorite += 1;
            $db_brand->save();
        }

        $data = [
            'subscribed' => $subscribed
        ];

        return $this->output( $data );
    }
}

app/Http/Controllers/Front/Heng/BaseController.php
<?php

namespace App\Http\Controllers\Front\Heng;

use App\Http\Controllers\BlankController;
use Illuminate\Http\Request;

use App\Models\Announcement;
use App\Models\Information;
use App\Models\Setting;
use App\Models\Brand;
use App\Models\Retailer;
use Artesaos\SEOTools\Traits\SEOTools as SEOToolsTrait;

class BaseController extends BlankController
{
	use SEOToolsTrait;

	public function __construct( Request $r )
	{
		parent::__construct( $r );
	}

    protected function generateMetaSEO()
    {
        $this->seo()->opengraph()->setUrl(url()->current());
    }

	protected function beforeOutput()
	{
        $this->generateMetaSEO();

		$st_setting 			= Setting::first();
		$st_footer_information 	= Information::published()->showFooter()->orderBy( 'sort_order', 'asc' )->take(8)->get();

		$st_footer_brands  		= Brand::published()->featured()->orderBy( 'sort_order', 'asc' )->take(8)->get();
		$st_footer_retailers 	= Retailer::published()->orderBy( 'created_at', 'desc' )->take(8)->get();

		$st_announcements 		= Announcement::published()->orderBy( 'created_at', 'desc' )->take(5)->get();

		return [
			'authed_user' 	 		=> \Auth::user(),
			'st_setting' 	 		=> $st_setting,
			'st_footer_brands' 		=> $st_footer_brands,
			'st_footer_retailers' 	=> $st_footer_retailers,
			'st_footer_info' 		=> $st_footer_information,
			'st_announcements' 		=> $st_announcements
		];
	}

}

app/Http/Controllers/Front/Heng/CategoryController.php
<?php

namespace App\Http\Controllers\Front\Heng;

class CategoryController extends BaseController
{
	public function index()
	{

		$data = compact( '' );
		return $this->output( 'f.heng.categories.index', $data );
	}
}

app/Http/Controllers/Front/Heng/QRController.php
<?php

namespace App\Http\Controllers\Front\Heng;

class QRController extends BaseController
{
	public function index()
	{
		$data = [];
		return $this->output( 'f.heng.scan-qr.index', $data );
	}
}

resources/views/f/heng/users/address-list.blade.php
@extends('f.heng.base')

@section( 'head_page_css' )
    @parent
    {!! html_css( 'heng/user-address-list.css' ) !!}
@stop

@section( 'low_padding_body', 'st-lower' )

@section( 'page_content' )

<div class="st-container with-margin">

    <section id="content_wrapper">

        @if( html_message_is_valid() )
            <div class="ct-error-info show-panel pad-bottom {{ html_add_error_class( 'txt-error', 'txt-valid' ) }}">
                {{ html_get_first_message() }}
            </div>
        @endif

        <div class="db-head">
            <a href="{{ route( 'f.heng.users.address_edit' ) }}" class="button">
                + Add Address
            </a>
            <a href="{{ route( 'f.heng.users.my_account' ) }}" class="button red">
                Back
            </a>
        </div>

        <div class="db-content">
            @if( $db_address->isEmpty() )
                <div class="ct-no-data slim-bottom no-border-top">
                    <div class="texts">{{ __('messages.data.no_address') }}</div>
                </div>
            @else

            <ul class="list">
                @foreach( $db_address as $r )
                <li class="item">
                    <div class="name bold">{{ $r->address_label }}</div>
                    <div class="name">
                        <p>
                            {{ $r->address }}<br/><br/>
                            Unit No: {{ $r->unit_no }}<br/>
                            Postal Code: {{ $r->postal_code}}
                        </p>
                    </div>
                    <div class="name">
                        @if( $r->isDefaultAddress() )
                            <span class="ct-txt-link orange no-padding-left nohoverunderline">Current Address</span>|
                            <a href="{{ route( 'f.heng.users.address_edit', $r->id ) }}" class="ct-txt-link blue">Edit</a>
                        @else
                            <a href="{{ route( 'f.heng.users.address_default_store', $r->id ) }}" class="ct-txt-link blue no-padding-left">Set Default</a>|
                            <a href="{{ route( 'f.heng.users.address_edit', $r->id ) }}" class="ct-txt-link blue">Edit</a>|
                            <a href="{{ route( 'f.heng.users.address_delete', $r->id ) }}" class="ct-txt-link red btn_cancel">Delete</a>
                        @endif
                    </div>
                </li>
                @endforeach
            </ul>
            @endif
        </div>

    </section>

</div>

@stop

@section( 'footer_content' )
    @include( 'f.heng.layouts._footer_min' )
@stop

@section( 'foot_page_js' )
    @parent
    <!-- Include jQuery - see http://jquery.com -->
    <script type="text/javascript">
        $(function()
        {

            $( ".btn_cancel" ).on( "click", function( e )
            {
                var $checkboxes = $( ".css-checkbox.nodel" );
                for( var i = 0, len = $checkboxes.length; i < len; i++ )
                {
                    let $checkbox = $checkboxes.eq( i );
                    if( $checkbox.is( ":checked" ) )
                    {
                        alert( "Participation for lucky draw with a receipt can not be cancelled");
                        e.preventDefault();
                        return false;
                    }
                }

                return confirm('Are you sure you want to delete address?');
            });

        });
    </script>
@stop

resources/views/f/heng/users/my_account.blade.php
@extends('f.heng.base')

@section( 'head_page_css' )
	@parent

	{!! html_css( 'heng/users.css' ) !!}
    {!! html_css( 'anypicker/dist/anypicker-all.min.css', 'js/vendors' ) !!}
@stop

@section( 'low_padding_body', 'st-lower' )

@section( 'page_content' )

<section id="user_content" class="st-container" >

	@include( 'f.heng.users.partials._navigation' )

	<section class="ct-panel over-width">
        @if( html_get_first_error_message() )
            <div class="ct-error-info show-panel pad-bottom {{ html_add_error_class() }}">
                {{ html_get_first_error_message() }}
            </div>
        @endif
        
		<div>

            <div class="ct-page-header margined">
                <h1>
                    Update Profile
                </h1>
                <span class="cph-bar"></span>
            </div>

			<div id="my_account_box">
				{!! form_open_post( route( 'f.heng.users.photo_upload' ), [ 'id'=>'form_photo' ], true ) !!}
					<div class="mc-upload-photo">
						<input type="file" id="photo_upload" class="ct-upload-button" name="photo_upload" accept="image/*"/>
						<label for="photo_upload">
						@if( !$authed_user->profile_img() )
							{!! html_img_site( 'upload-photo.png',
							[
								'w' => 200,
								'h' => 200,
							]) !!}
						@else
							<img src="{{ $authed_user->profile_img() }}" alt="{{ $authed_user->full_name }}" title="{{ $authed_user->full_name }}" width="200" height="200" class="ct-image-rounded">
						@endif
						</label>
						<div class="upload-title">
							Upload Profile Picture
						</div>
 					</div>
				{!! form_close() !!}

    			{!! form_open_post( route( 'f.heng.users.my_account' ) ) !!}
					@php $error_msg = html_get_first_error_message() @endphp
					<div class="ct-form medium">

						<div class="ctf-row">
							<label for="ctf-name">
								Name
								<span class="cr-asterisk">*</span>
							</label>
							<div class="cr-multi-info">
								<input type="text" name="name" id="ctf-name" class="cr-input" value="{{ form_set_value( 'name', $authed_user->full_name ) }}" placeholder="Name as per NRIC/FIN">
								<div class="information">(For verification when you win)</div>
							</div>
						</div>
						<div class="ctf-row">
							<label for="ctf-email">Email</label>
							<div class="cr-multi-info">
								<input type="text" name="email" id="ctf-email" class="cr-input" value="{{ form_set_value( 'email', $authed_user->email ) }}" disabled="disabled" placeholder="Fill your email">
								@if( $authed_user->is_verified != 1)
									<a href="{{ route( 'f.heng.users.resend_verification' ) }}" class="information redirect">Resend verification email.</a>
								@endif
							</div>
						</div>
						<div class="ctf-row">
							<label for="ctf-mobile-number">
								Mobile Number
								<span class="cr-asterisk">*</span>
							</label>
							<div class="cr-multi-info">
								<input type="text" maxlength="8" name="mobile_number" id="ctf-mobile-number" class="prevent_chars cr-input no-spin" value="{{ form_set_value( 'mobile_number', $authed_user->phone_number ) }}" placeholder="8-digit Mobile No.">
								<div class="information">(Fill in Correct Mobile No to contact you when you win)</div>
							</div>
						</div>
                        <div class="ctf-row">
                            <label for="ctf-id-number">
                                Gender
                                <span class="cr-asterisk">*</span>
                            </label>
                            <div class="cr-multi-info">
                            	<div class="cr-radio top">
									<input type="radio" name="gender" value="male" id="male" class="bullet" 
									@if(old('gender') == 'male' ) checked @endif
									@if( $authed_user->gender == 'male' ) checked @endif
									>
									<label for="male">Male</label>
								</div>
								<div  class="cr-radio" >
									<input type="radio" name="gender" value="female" id="female" class="bullet"
									@if(old('gender') == 'female' ) checked @endif
									@if( $authed_user->gender == 'female' ) checked @endif
									>
									<label for="female">Female</label>
								</div>
                            </div>
                        </div>
                        <div class="ctf-row">
                            <label for="ctf-id-number">
                                Date of Birth
                                <span class="cr-asterisk">*</span>
                            </label>
                            <div class="cr-multi-info">
                                <input type="text" readonly="readonly" name="date_of_birth" id="ctf_dob" class="cr-input" value="{{ form_set_value( 'date_of_birth', $user->dob ) }}" placeholder="Fill your date of birth">
								<div class="information">(For verification when you win)</div>
                            </div>
                        </div>
						<div class="ctf-row">
							<label for="ctf-postal">
								Postal Code
								<span class="cr-asterisk">*</span>
							</label>
							<div class="cr-multi-info">
								<input type="text" maxlength="6" name="postal_code" id="ctf-postal" class="prevent_chars cr-input" value="{{ form_set_value( 'postal_code', $authed_user->postal_code ) }}" placeholder="Key in postal code">
							</div>
						</div>

						<div class="ctf-row">
							<label for="ctf-address">
								Address
								<span class="cr-asterisk">*</span>
							</label>
							<div class="cr-multi-info">
								<textarea name="address" class="cr-input textarea" placeholder="Block & Street Address">{{ form_set_value( 'address', $authed_user->address ) }}</textarea>
							</div>
						</div>
						<div class="ctf-row">
							<label for="ctf-unit">
								Unit No
								<span class="cr-asterisk">*</span>
							</label>
							<div class="cr-multi-info">
								<input type="text" name="unit_no" id="ctf-unit" class="cr-input" value="{{ form_set_value( 'unit_no', $authed_user->unit_no ) }}" placeholder="Fill your unit no">
							</div>
						</div>
                        <div class="ctf-row-checkbox">
							<input type="checkbox" name="promo_email" id="promo_email" class="css-checkbox" value="1" 
							@if( old('promo_email') == 1 || $authed_user->promo_email == 1 && empty( $error_msg) )checked="checked"@endif />
							<label for="promo_email" class="css-label">
		                        Yes! I would like to receive updates about lucky draws and promotions from Shop&Win via email.
							</label>
                        </div>
						<input type="submit" name="save" value="Save" class="cr-button f-right">
					</div>
   				{!! form_close() !!}

			</div>

		</div>
	</section>

</section>

@stop

@section( 'footer_content' )
	@include( 'f.heng.layouts._footer_min' )
@stop

@section( 'foot_page_js' )
	@parent
    {!! html_js( 'js/vendors/anypicker/dist/anypicker.min.js' ) !!}
	{!! html_js( 'js/vendors/owl.carousel/dist/owl.carousel.min.js' ) !!}
	{!! html_js( 'js/f/mobile-owl-carousel.js' ) !!}
	<script>
		$(function()
		{
			$( "#photo_upload" ).on( "change", function()
			{
				var file = this.files[0];
				var fileType = file["type"];
				var ValidImageTypes = [ "image/jpeg", "image/png"];
				if ($.inArray(fileType, ValidImageTypes) < 0) {
     				alert( "Uploaded photo must be only in jpeg or png format." );
				}
				else
				{
					$(this).parents( "form" ).first().submit();
				}
			});

            var $dates = $( "#ctf_dob" );
            for( var i = 0, len = $dates.length; i < len; i++ )
            {
                var $date = $dates.eq( i ),

                val = $date.val();

                $date.AnyPicker(
                {
                    dateTimeFormat      : "dd MMMM YYYY",
                    selectedDate        : val,
					minValue 			: new Date(1920, 01, 19),
                    animationDuration   : 300,
                    maxValue            : new Date()
                });	
            }
		});
	</script>
@stop